version : '3'
services:
  nginx:
    image: nginx:1.19.5
    ports:
      - "9990:80"
    volumes:
      - .:/home/sample-rest-api
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - static-volumn:/data/static
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn common.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/home/sample-rest-api
      - static-volumn:/home/sample-rest-api/staticfiles
    expose:
      - "8000"

volumes:
  static-volumn: