# Generated by Django 3.2.4 on 2021-06-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('code_name', models.CharField(max_length=100, null=True)),
                ('sort_seq', models.IntegerField()),
                ('use_yn', models.BooleanField()),
                ('remark', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
